### ISSUE TITLE
Increase Niederlande mbtiles to cover whole Netherlands

### ISSUE THREAD

**Issue by marcelrv** [stevo01/SeaChartCreator#2]
Would be great if the current Niederlande-Binnen could be updated to include the whole of the Netherlands. Now it just excludes parts where I'm normally sailing (in the North around Terschellingen and in the south near zeeland)

The next map `NorthSea` covers the area as well but has less details available.

**Comment by stevo01** [comment]
I created own repository for the "map projetct files" in openseamap project. 
see https://github.com/OpenSeaMap/chart-projectfiles for details.
Feel free to update "map projetct files" and send a pull request to that repository.
